spring.application.name=BookmarkApp

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/bookmarkAppDB
spring.datasource.username=root
spring.datasource.password=3416
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=335e7b3cbb72bd
spring.mail.password=d332f5b06c3909
spring.mail.properties.mail.smtp.auth=PLAIN