spring.application.name=classworkapp

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=335e7b3cbb72bd
spring.mail.password=d332f5b06c3909
spring.mail.properties.mail.smtp.auth=PLAIN